// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IoBuffer.proto

#include "IoBuffer.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace IoBuffer {
template <typename>
PROTOBUF_CONSTEXPR Summary::Summary(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ravrg_)*/ 0u

  , /*decltype(_impl_.rstd_)*/ 0u

  , /*decltype(_impl_.wavrg_)*/ 0u

  , /*decltype(_impl_.wstd_)*/ 0u

  , /*decltype(_impl_.rsize_)*/ 0u

  , /*decltype(_impl_.wsize_)*/ 0u

  , /*decltype(_impl_.riops_)*/ 0

  , /*decltype(_impl_.wiops_)*/ 0
} {}
struct SummaryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SummaryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SummaryDefaultTypeInternal() {}
  union {
    Summary _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SummaryDefaultTypeInternal _Summary_default_instance_;
}  // namespace IoBuffer
static ::_pb::Metadata file_level_metadata_IoBuffer_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_IoBuffer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_IoBuffer_2eproto = nullptr;
const ::uint32_t TableStruct_IoBuffer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.ravrg_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.rstd_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.wavrg_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.wstd_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.rsize_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.wsize_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.riops_),
    PROTOBUF_FIELD_OFFSET(::IoBuffer::Summary, _impl_.wiops_),
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 16, -1, sizeof(::IoBuffer::Summary)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::IoBuffer::_Summary_default_instance_._instance,
};
const char descriptor_table_protodef_IoBuffer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016IoBuffer.proto\022\010IoBuffer\"\177\n\007Summary\022\r\n"
    "\005rAvrg\030\001 \001(\r\022\014\n\004rstd\030\002 \001(\r\022\r\n\005wAvrg\030\003 \001("
    "\r\022\014\n\004wstd\030\004 \001(\r\022\r\n\005rSize\030\005 \001(\r\022\r\n\005wSize\030"
    "\006 \001(\r\022\r\n\005rIops\030\007 \001(\001\022\r\n\005wIops\030\010 \001(\001"
};
static ::absl::once_flag descriptor_table_IoBuffer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_IoBuffer_2eproto = {
    false,
    false,
    155,
    descriptor_table_protodef_IoBuffer_2eproto,
    "IoBuffer.proto",
    &descriptor_table_IoBuffer_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_IoBuffer_2eproto::offsets,
    file_level_metadata_IoBuffer_2eproto,
    file_level_enum_descriptors_IoBuffer_2eproto,
    file_level_service_descriptors_IoBuffer_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_IoBuffer_2eproto_getter() {
  return &descriptor_table_IoBuffer_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_IoBuffer_2eproto(&descriptor_table_IoBuffer_2eproto);
namespace IoBuffer {
// ===================================================================

class Summary::_Internal {
 public:
  using HasBits = decltype(std::declval<Summary>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Summary, _impl_._has_bits_);
  static void set_has_ravrg(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_rstd(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_wavrg(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_wstd(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_rsize(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_wsize(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_riops(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_wiops(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
};

Summary::Summary(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:IoBuffer.Summary)
}
Summary::Summary(const Summary& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:IoBuffer.Summary)
}

inline void Summary::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ravrg_) { 0u }

    , decltype(_impl_.rstd_) { 0u }

    , decltype(_impl_.wavrg_) { 0u }

    , decltype(_impl_.wstd_) { 0u }

    , decltype(_impl_.rsize_) { 0u }

    , decltype(_impl_.wsize_) { 0u }

    , decltype(_impl_.riops_) { 0 }

    , decltype(_impl_.wiops_) { 0 }

  };
}

Summary::~Summary() {
  // @@protoc_insertion_point(destructor:IoBuffer.Summary)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Summary::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void Summary::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Summary::Clear() {
// @@protoc_insertion_point(message_clear_start:IoBuffer.Summary)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&_impl_.ravrg_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.wiops_) -
        reinterpret_cast<char*>(&_impl_.ravrg_)) + sizeof(_impl_.wiops_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Summary::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 rAvrg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_ravrg(&has_bits);
          _impl_.ravrg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 rstd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_rstd(&has_bits);
          _impl_.rstd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 wAvrg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _Internal::set_has_wavrg(&has_bits);
          _impl_.wavrg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 wstd = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _Internal::set_has_wstd(&has_bits);
          _impl_.wstd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 rSize = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _Internal::set_has_rsize(&has_bits);
          _impl_.rsize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 wSize = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 48)) {
          _Internal::set_has_wsize(&has_bits);
          _impl_.wsize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double rIops = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 57)) {
          _Internal::set_has_riops(&has_bits);
          _impl_.riops_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double wIops = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 65)) {
          _Internal::set_has_wiops(&has_bits);
          _impl_.wiops_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Summary::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IoBuffer.Summary)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 rAvrg = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_ravrg(), target);
  }

  // optional uint32 rstd = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_rstd(), target);
  }

  // optional uint32 wAvrg = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_wavrg(), target);
  }

  // optional uint32 wstd = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_wstd(), target);
  }

  // optional uint32 rSize = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_rsize(), target);
  }

  // optional uint32 wSize = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_wsize(), target);
  }

  // optional double rIops = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        7, this->_internal_riops(), target);
  }

  // optional double wIops = 8;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        8, this->_internal_wiops(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IoBuffer.Summary)
  return target;
}

::size_t Summary::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IoBuffer.Summary)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional uint32 rAvrg = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_ravrg());
    }

    // optional uint32 rstd = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_rstd());
    }

    // optional uint32 wAvrg = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_wavrg());
    }

    // optional uint32 wstd = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_wstd());
    }

    // optional uint32 rSize = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_rsize());
    }

    // optional uint32 wSize = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_wsize());
    }

    // optional double rIops = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 9;
    }

    // optional double wIops = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 9;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Summary::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Summary::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Summary::GetClassData() const { return &_class_data_; }


void Summary::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Summary*>(&to_msg);
  auto& from = static_cast<const Summary&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:IoBuffer.Summary)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.ravrg_ = from._impl_.ravrg_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.rstd_ = from._impl_.rstd_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.wavrg_ = from._impl_.wavrg_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.wstd_ = from._impl_.wstd_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.rsize_ = from._impl_.rsize_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.wsize_ = from._impl_.wsize_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.riops_ = from._impl_.riops_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.wiops_ = from._impl_.wiops_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Summary::CopyFrom(const Summary& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IoBuffer.Summary)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Summary::IsInitialized() const {
  return true;
}

void Summary::InternalSwap(Summary* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Summary, _impl_.wiops_)
      + sizeof(Summary::_impl_.wiops_)
      - PROTOBUF_FIELD_OFFSET(Summary, _impl_.ravrg_)>(
          reinterpret_cast<char*>(&_impl_.ravrg_),
          reinterpret_cast<char*>(&other->_impl_.ravrg_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Summary::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_IoBuffer_2eproto_getter, &descriptor_table_IoBuffer_2eproto_once,
      file_level_metadata_IoBuffer_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace IoBuffer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::IoBuffer::Summary*
Arena::CreateMaybeMessage< ::IoBuffer::Summary >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IoBuffer::Summary >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
